# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 420b800fab2856c4d169b8947e4eb560af09d08ccd221ddc759b63bff1e38e30dd553ed537987037a7bd65a6e354e0ff31be5032a51876bf3e5dee70d6fa5b1f

test:
  secret_key_base: c11eb379541e4fd3000e944dadf95697d06bf8f9b36c13c3745d8bb0c529b46c8695af0ebe476a92363dfc953918c01f59bb004439ca2d45b89ab96632ef7764

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
